name: py lint
on:
  pull_request:
    branches:
      - main
jobs:
  py_lint:
    name: py lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install requirements
        run: pip3 install -r requirements.txt
      - name: install pylint
        run: pip3 install pylint
      - name: pylint
        run: pylint --rcfile=.pylintrc opengemini_client
